### ISSUE TITLE
更新参数接口能否针对某些或某个组件进行更新

### ISSUE THREAD

**Issue by gm100861** [FederatedAI/FATE-Flow#146]
**System information**
- FATE Flow version (use command: python fate_flow_server.py --version):
- 1.7
- Python version (use command: python --version):
- 3.6.10

在更新参数接口 /parameter/update, 能否做到判断具体时那些参数更新了，影响了那些组件，并为这些组件生成新的版本任务，然后找到本修改的最上游的组件，从这个组件从新运行job会比较合理。我看了1.7的代码发现修改参数时要传入修改后完整的配置，哪怕我只修改了一个组件。代码里面也有修改组件的变量但是没有实现相关逻辑。想问下设计这个参数修改时的初衷是什么。后续是否会实现我描述的功能

**Comment by jarviszeng-zjc** [comment]
Maybe you've been looking at the code branch for a long time, In the v1.7.0, it will be
1. Only input the parameters that need to be updated for a component or multiple components, and the interface will return all the parameters of the component after the update is completed, including custom parameters and default parameters
2. Use the rerun CLI/API to specify that the component with updated parameters will be rerun and that components that depend on it will be rerun, while other components will not be rerun

[reference](https://fate-flow.readthedocs.io/en/latest/zh/fate_flow_job_scheduling/#8)
