### ISSUE TITLE
Document issue: parameter in `flow table` should be `table-name` instead of `name`

### ISSUE THREAD

**Issue by gxcuit** [FederatedAI/FATE-Flow#175]
The `table `parameter of `flow client cli` in the current version(1.7) has changed to `table-name` ， Pease refer to https://github.com/gxcuit/FATE/blob/6a9c2dd6ff95fcab6f336a2e188a0c58f3777d39/python/fate_client/flow_client/flow_cli/utils/cli_args.py#L78

However, the [doc ](https://github.com/FederatedAI/FATE-Flow/blob/b3393eef78646afc607df29871aecf2a96032d65/doc/cli/table.md)still uses `name`.

**Contributing**

- Do you want to contribute a PR? (yes/no): Yes
- Briefly describe your candidate solution(if contributing):

**Comment by zhihuiwan** [comment]
thanks
