### ISSUE TITLE
关于model_local_cache目录下的模型及jobs目录下的job相关配置文件是否有自动清理的机制？

### ISSUE THREAD

**Issue by MiKKiYang** [FederatedAI/FATE-Flow#205]
有个问题想请教下，fate1.7.x版本目前有对model_local_cache目录里的模型以及jobs目录里的历史job相关配置文件自动清理的处理吗？就是下图中红线标出的，我在1.7.2fateflow源码中看了下，貌似没找到，但是无法确定，包括后续1.8版本中是否会增加这俩目录的自动清理呢？希望得到你的答复
![image](https://user-images.githubusercontent.com/38832234/158770300-da8a0b16-0082-408a-a910-c6f240ecb7aa.png)

_Originally posted by @MiKKiYang in https://github.com/FederatedAI/FATE-Flow/issues/204#issuecomment-1070540116_

**Comment by jat001** [comment]
目前没有自动清理的功能

**Comment by MiKKiYang** [comment]
@jat001 @jarviszeng-zjc @dylan-fan @hainingzhang hope to get ur help，tks ~~~

**Comment by MiKKiYang** [comment]
> 目前没有自动清理的功能

tks jat!!! 不知道后续版本有考虑规划这块的自动清理功能吗？还是说从fate的设计理念来说，不打算增加这个功能（因为fate更多是定位为联邦学习的引擎内核），自动清理功能由fate引擎上层的联邦学习产品做包装处理？

**Comment by MiKKiYang** [comment]
> > 目前没有自动清理的功能
> 
> tks jat!!! 不知道后续版本有考虑规划这块的自动清理功能吗？还是说从fate的设计理念来说，不打算增加这个功能（因为fate更多是定位为联邦学习的引擎内核），自动清理功能由fate引擎上层的联邦学习产品做包装处理？

@jat001
