### ISSUE TITLE
homo_nn使用pipeline加验证集后错误

### ISSUE THREAD

**Issue by Mr-lq7** [FederatedAI/FATE-Flow#221]
arbiter方报错。
报错信息如下：
<img width="958" alt="微信截图_20220402223046" src="https://user-images.githubusercontent.com/52699164/161387955-4421599d-2966-4fd1-b907-bfafc2599693.png">
pipeline代码（添加验证集后错误，reader_0是训练集，reader_1是验证集）
<img width="643" alt="微信截图_20220402223329" src="https://user-images.githubusercontent.com/52699164/161388033-0080d47f-5545-4aee-b858-141f0d26499b.png">
在代码逻辑完全一致的情况下，跑home_lr是没问题的，跑homo_nn出现了问题

**Comment by zhihuiwan** [comment]
homo_NN不支持验证集
