### ISSUE TITLE
如果想要当前作业各个参与方都完成bind操作，是否需要手动调用各方的bind接口执行后才ok？

### ISSUE THREAD

**Issue by MiKKiYang** [FederatedAI/FATE-Flow#229]
模型部署加载绑定过程中，部署deploy，加载load从源码实现看都是从guest发起调用后，会将请求通过rollsite分发给当前作业中其他参与方进行调用执行，达到在guest方进行deploy、load后，其余参与方也执行了相应的deploy、load操作
但是bind接口从源码实现看并没有将bind请求分发给各个参与方的操作
那么如果想要当前作业各个参与方都完成bind操作，是否需要手动调用各方的bind接口执行后才ok？

**Comment by MiKKiYang** [comment]
问题如果代码确实是这样实现的，为什么要这样实现呢？
如果deploy、load接口，都是支持从guest方调用后，guest会将同样的请求走rollsite分发给其余参与方执行
那么bind接口为什么不做同样的处理，反而要在各方分别进行bind接口调用呢？
@jat001 @dylan-fan @jarviszeng-zjc @hainingzhang   各位，确实疑惑，请不吝赐教哈~

**Comment by MiKKiYang** [comment]
还是说：guest 根据自己bind得到的serviceid 就可以得到模型的全部信息，包含host那边的信息？所以模型在推理集群的部署加载只需要load就可以了？

**Comment by dylan-fan** [comment]
bind 是绑定serviceid。serviceid进对guest有用。所有不用各方都执行该操作。
