### ISSUE TITLE
JobDefaultConfig.upload_max_bytes配置无效

### ISSUE THREAD

**Issue by zhanhtCN** [FederatedAI/FATE-Flow#231]
fate 1.7.0版本
配置中，upload_max_bytes是4194304000
<img width="465" alt="image" src="https://user-images.githubusercontent.com/96578077/164958520-dc878496-163b-4968-ab82-d09637c3daf1.png">

但是upload组件打印日志，发现upload_max_bytes是104857600
<img width="1166" alt="image" src="https://user-images.githubusercontent.com/96578077/164958497-8f8cea53-f3c9-43c3-8822-56651282c886.png">

**Comment by zhihuiwan** [comment]
上传时采用分块put，这个配置实际是每一块的大小。配置命名有点歧义，后面我们换个名字。

**Comment by zhanhtCN** [comment]
> 上传时采用分块put，这个配置实际是每一块的大小。配置命名有点歧义，后面我们换个名字。

你好，我upload发现网速成为了瓶颈，这个有啥加速的配置或者方法吗？
900w行数据，42G，16partiton，upload 40min
![image](https://user-images.githubusercontent.com/96578077/165206988-afb46f5a-1e76-45f0-b9b9-13272a26ca63.png)

**Comment by zhanhtCN** [comment]
> > 上传时采用分块put，这个配置实际是每一块的大小。配置命名有点歧义，后面我们换个名字。
> 
> 你好，我upload发现网速成为了瓶颈，这个有啥加速的配置或者方法吗？ 900w行数据，42G，16partiton，upload 40min ![image](https://user-images.githubusercontent.com/96578077/165206988-afb46f5a-1e76-45f0-b9b9-13272a26ca63.png)

过程中，机器的磁盘和cpu都没太大波动，主要是这个网络流量限制了速度，
为啥会有网络流量，我理解这个即使有，也是内部局域网吧，容器间的网络传输？
如何可以更加充分的利用网速？

**Comment by zhanhtCN** [comment]
@zhihuiwan 求大佬帮忙看看

**Comment by jat001** [comment]
> > 上传时采用分块put，这个配置实际是每一块的大小。配置命名有点歧义，后面我们换个名字。
> 
> 你好，我upload发现网速成为了瓶颈，这个有啥加速的配置或者方法吗？ 900w行数据，42G，16partiton，upload 40min ![image](https://user-images.githubusercontent.com/96578077/165206988-afb46f5a-1e76-45f0-b9b9-13272a26ca63.png)

这是某个 interface 还是总流量，如果是总流量，我怀疑是 loopback

**Comment by zhanhtCN** [comment]
总的吧，这是机器层面的监控，所以upload就是会走网卡？

**Comment by jat001** [comment]
> 总的吧，这是机器层面的监控，所以upload就是会走网卡？

设计原因，基本所有api都会走localhost

**Comment by zhanhtCN** [comment]
> > 总的吧，这是机器层面的监控，所以upload就是会走网卡？
> 
> 设计原因，基本所有api都会走localhost

那请问当前这个upload操作可以通过改什么配置，或其他方式，把速度提上去呢？感觉当前网速没利用充分

**Comment by SnakeCN21** [comment]
> fate 1.7.0版本 配置中，upload_max_bytes是4194304000 <img alt="image" width="465" src="https://user-images.githubusercontent.com/96578077/164958520-dc878496-163b-4968-ab82-d09637c3daf1.png">
> 
> 但是upload组件打印日志，发现upload_max_bytes是104857600 <img alt="image" width="1166" src="https://user-images.githubusercontent.com/96578077/164958497-8f8cea53-f3c9-43c3-8822-56651282c886.png">

老哥, 你有解决方案吗? 我也遇到一样的问题了, job default config not supported upload_max_bytes, 在 reader 就挂了

**Comment by jat001** [comment]
@SnakeCN21 是1.9.0吗？
