### ISSUE TITLE
FATE后端使用spark_rabbitmq无法运行示例任务的问题

### ISSUE THREAD

**Issue by wsptfb** [FederatedAI/FATE-Flow#236]
在KubeFATE的v1.8.0版本的docker-deploy部署方法中，使用两台虚拟机，使用eggroll可以正常运行示例流程；使用spark和rabbitmq无法运行示例数据。

为了使用spark和rabbitmq，根据收集的信息，
1. 首先修改parties.conf文件中的backend=spark_rabbitmq
![image](https://user-images.githubusercontent.com/53591060/167246540-60cb5de2-d898-420c-8de3-17ee043cfab8.png) 

2. 然后修改training_template/public/fate_flow/conf/service_conf.yaml文件中的default_engines部分，
分别设置为 computing: spark   federation: rabbitmq   storage: hdfs
![1651914151(1)](https://user-images.githubusercontent.com/53591060/167247347-762a0ffb-6f6d-4bba-ab82-67afd5b33d3f.jpg)

3. 修改完成后，分别运行generate_config.sh和docker_deploy.sh all命令，在两台虚拟机上启动了所有docker容器。在host端进入client_1容器，修改fateflow/examples/upload/upload_host.json文件，在最后添加”storage_engine“: "HDFS"后，使用flow data upload 提交数据
![image](https://user-images.githubusercontent.com/53591060/167247428-26d0753c-e757-48ff-a632-a54eaf4af091.png)

4. 在guest端以同样的方式修改upload_guest.json文件，添加”storage_engine“: "HDFS"后，使用flow data upload 提交数据。然后修改fateflow/examples/lr/test_hetero_lr_job_conf.json文件，在job_parameters中提交”spark_run“和"rabbitmq_run"的配置信息
![image](https://user-images.githubusercontent.com/53591060/167247390-3b95159d-24a7-4aa5-a82c-4061d904120c.png)

6. 使用命令flow job submit提交任务
![image](https://user-images.githubusercontent.com/53591060/167246944-c7b0c6e1-5922-47bc-ac80-7bab3e781151.png)

整个流程没有报错信息，但是提交任务后，所有的f_status一直处于waiting状态，训练流程无法运行。请问有可能是什么问题导致上述任务无法运行的情况？？？

**Comment by zhihuiwan** [comment]
job日志下面有没有报错信息？
