### ISSUE TITLE
使用flow table bind命令连接mysql无法获取数据和连接hdfs报错

### ISSUE THREAD

**Issue by wsptfb** [FederatedAI/FATE-Flow#341]
使用的fate版本是1.9.0，在三个虚拟机上以分布式方式启动，后端计算和存储引擎是eggroll.

1. 连接mysql无法获取表内数据
mysql应用程序基于docker镜像mysql:5.7在另一台虚拟机上启动，在数据库huian的test表中插入建模用的数据。test表内数据如下所示，
![image](https://user-images.githubusercontent.com/53591060/195287636-a862ad16-0ac5-4723-b453-1ac350f064aa.png)
进入fate中一方节点的confs-xxx_client_1容器内，编写用于mysql数据库连接的json文件并命名为data.json，如下所示，
![image](https://user-images.githubusercontent.com/53591060/195288311-12cd5806-2bed-4c1a-bc2d-60029537cc68.png)
使用flow table bind -c data.json命令后，可以和远程数据库建立连接，但是使用flow table info命令查询数据表中没有数据，返回结果的count字段值为null，无法使用该DTable表中数据进行建模任务。
![image](https://user-images.githubusercontent.com/53591060/195289432-18848ee3-9a7e-47a0-8be9-9b533225a55e.png)
请问需要如何修改data.json文件，才可以把mysql表中的数据加载到fate存储系统中，还是需要再使用完flow table bind -c data.json命令后，还需要使用其他命令来加载数据到fate存储系统中？

2. 连接hdfs后报错
hdfs通过singularities/hadoop:latest（hadoop版本应该是2.8.3）镜像在一台虚拟机上启动，包括一个namenode和3个datanode节点。编写用于数据系统映射的data.json文件如下所示，
![image](https://user-images.githubusercontent.com/53591060/195291341-9da35a0e-c047-4fac-b899-15df61cf736f.png)
使用flow table bind -c data.json报错，如下所示，
![image](https://user-images.githubusercontent.com/53591060/195291825-d651b045-979f-4fda-ba86-589f917a3950.png)
请问需要如何配置可以正确导入hdfs中的文件？

**Comment by zhihuiwan** [comment]
1. table bind 不会加载数据，所以count会显示空。当table bind的数据经过reader处理之后，会更新其meta的count。
无法使用该DTable表中数据进行建模任务--能提供下具体报错内容吗？
2. fate 1.9版本升级了python依赖至3.8版本，对应的hadoop推荐使用3.x版本，fate 1.9对应hadoop的测试版本是3.3.1

**Comment by wsptfb** [comment]
1 我们的理解是，使用flow table bind命令可以把远程mysql数据库中的表，读入到fate的DTable中供建模使用，和使用flow data upload命令加载fate中的csv文件到DTable中的效果一样。flow table bind命令是不是具有上述功能？
根据上一封邮件内容显示，如果flow table bind不会加载数据，那么是不是只能通过flow data upload命令把csv文件中的数据读取到DTable中，不支持其他加载数据到DTable的模式？
















在 2022-11-14 14:28:54，"zhihuiwan" ***@***.***> 写道：

table bind 不会加载数据，所以count会显示空。当table bind的数据经过reader处理之后，会更新其meta的count。
无法使用该DTable表中数据进行建模任务--能提供下具体报错内容吗？
fate 1.9版本升级了python依赖至3.8版本，对应的hadoop推荐使用3.x版本，fate 1.9对应hadoop的测试版本是3.3.1
