### ISSUE TITLE
V1.9版本的预测任务使用modelLoader加载其他的model时异常

### ISSUE THREAD

**Issue by momingzhi0303** [FederatedAI/FATE-Flow#343]
V1.9版本 fate-flow/python/fate_flow/pipelined_model/pipelined_model.py的【read_component_model】方法新增了以下逻辑：
       
<img width="1155" alt="image" src="https://user-images.githubusercontent.com/38578656/197912659-eebda746-d529-40e4-8dc1-1fca23991f66.png">

**导致的问题**
在发起一个预测job时，如果job的dsl有用model_loader加载另一个已经deploy的model时，会找不到找不该model
![image](https://user-images.githubusercontent.com/38578656/197913418-af29400b-b967-4fd7-a0ea-9f22efecc1c0.png)

<img width="1229" alt="image" src="https://user-images.githubusercontent.com/38578656/197912110-394adb31-4486-46b4-bc8d-6dc61da05e53.png">

**目前的修复方案**
修改task_executor.py文件，修改后能正常运行
<img width="1184" alt="image" src="https://user-images.githubusercontent.com/38578656/197912474-d571cbf7-e0c3-4844-a042-81633777f4ef.png">
@jat001 @dylan-fan @jarviszeng-zjc @hainingzhang 看这种修复方案不知道是否有其他影响，能否在以后的版本中修复，期待您的回复

**Comment by jat001** [comment]
https://github.com/FederatedAI/FATE-Flow/commit/a80fd6963b2fa86ab0c4953b95f2d4fe192e785d
