### ISSUE TITLE
FATEFLOW使用tablebind的方式上传大量数据到HDFS的问题

### ISSUE THREAD

**Issue by shinobi6xp** [FederatedAI/FATE-Flow#369]
使用fate on spark的部署方式，后方使用的是cdh来管理spark和hdfs，在我绑定了一个hdfs的数据源，提交任务执行reader模块的时候，报了一个  put in hdfs file: hdfs://xxx.xxx:8020//fate/output_data/output_data_202212281410532503440_reader_0_1/db296378867711ed913f52540054dd30
360
[INFO] [2022-12-28 14:21:59,049] [202212281410532503440] [10546:140548273137472] - [_table._put_all] [line:64]: put in hdfs file: hdfs://xxx.xxx:8020//fate/output_data/output_data_202212281410532503440_reader_0_1/db296378867711ed913f52540054dd30
361
[ERROR] [2022-12-28 14:21:59,231] [202212281410532503440] [10546:140548273137472] - [task_executor._run_] [line:243]: HDFS CloseFile failed, errno: 255 (Unknown error 255) Please check that you are connecting to the correct HDFS RPC port
的错误，实际上hdfs的配置是没有问题。后来调查，发现put-all的方法被调用了两次，当第二次调用的时候，就会报这个错误。
查看代码，发现data_manager中的put_in_table方法有一个 max_num=10000的参数常量，看起来是为了控制数据使用内存使用的。但这个参数的不可变，导致了数据量很大的时候，hdfs发生了多线程写，于是报错。希望可以优化这个参数

**Comment by zhihuiwan** [comment]
1.11.0版本已经修复
