### ISSUE TITLE
使用fate1.9时，任务结束后clustermanager残留许多计算的进程

### ISSUE THREAD

**Issue by wvictors** [FederatedAI/FATE-Flow#408]
(app-root) bash-4.2# ps aux | grep python
root        340  0.1  0.0 1066072 2164 ?        Sl   10:07   0:04 /opt/app-root/bin/python python/eggroll/roll_pair/egg_pair.py --config /data/projects/fate/eggroll/conf/eggroll.properties --session-id 202302101007038548750_reader_0_0_guest_60003 --server-node-id 2 --cluster-manager clustermanager:4670 --node-manager 4671 --processor-id 13002
root        353  0.1  0.0 1066072 4012 ?        Sl   10:07   0:04 /opt/app-root/bin/python python/eggroll/roll_pair/egg_pair.py --config /data/projects/fate/eggroll/conf/eggroll.properties --session-id 202302101007038548750_reader_0_0_guest_60003 --server-node-id 2 --cluster-manager clustermanager:4670 --node-manager 4671 --processor-id 13006
root        359  0.1  0.0 1066072 2168 ?        Sl   10:07   0:04 /opt/app-root/bin/python python/eggroll/roll_pair/egg_pair.py --config /data/projects/fate/eggroll/conf/eggroll.properties --session-id 202302101007038548750_reader_0_0_guest_60003 --server-node-id 2 --cluster-manager clustermanager:4670 --node-manager 4671 --processor-id 13004
root        374  0.1  0.0 1139800 5256 ?        Sl   10:07   0:05 /opt/app-root/bin/python python/eggroll/roll_pair/egg_pair.py --config /data/projects/fate/eggroll/conf/eggroll.properties --session-id 202302101007038548750_reader_0_0_guest_60003 --server-node-id 2 --cluster-manager clustermanager:4670 --node-manager 4671 --processor-id 13001
root        381  0.1  0.0 1066072 2368 ?        Sl   10:07   0:04 /opt/app-root/bin/python python/eggroll/roll_pair/egg_pair.py --config /data/projects/fate/eggroll/conf/eggroll.properties --session-id 202302101007038548750_reader_0_0_guest_60003 --server-node-id 2 --cluster-manager clustermanager:4670 --node-manager 4671 --processor-id 13005
root        386  0.1  0.0 1066068 1876 ?        Sl   10:07   0:04 /opt/app-root/bin/python python/eggroll/roll_pair/egg_pair.py --config /data/projects/fate/eggroll/conf/eggroll.properties --session-id 202302101007038548750_reader_0_0_guest_60003 --server-node-id 2 --cluster-manager clustermanager:4670 --node-manager 4671 --processor-id 13003
root        707  0.1  0.0 1139804 2120 ?        Sl   10:07   0:04 /opt/app-root/bin/python python/eggroll/roll_pair/egg_pair.py --config /data/projects/fate/eggroll/conf/eggroll.properties --session-id 202302101007038548750_reader_0_0_guest_60003_storage_a4ce30c8-a8e7-11ed-92bc-0242c0a70064 --server-node-id 2 --cluster-manager clustermanager:4670 --node-manager 4671 --processor-id 13008
root        708  0.1  0.0 1066068 1972 ?        Sl   10:07   0:04 /opt/app-root/bin/python python/eggroll/roll_pair/egg_pair.py --config /data/projects/fate/eggroll/conf/eggroll.properties --session-id 202302101007038548750_reader_0_0_guest_60003_storage_a4ce30c8-a8e7-11ed-92bc-0242c0a70064 --server-node-id 2 --cluster-manager clustermanager:4670 --node-manager 4671 --processor-id 13010
root        712  0.1  0.0 1066072 2232 ?        Sl   10:07   0:05 /opt/app-root/bin/python python/eggroll/roll_pair/egg_pair.py --config /data/projects/fate/eggroll/conf/eggroll.properties --session-id 202302101007038548750_reader_0_0_guest_60003_storage_a4ce30c8-a8e7-11ed-92bc-0242c0a70064 --server-node-id 2 --cluster-manager clustermanager:4670 --node-manager 4671 --processor-id 13007
root        720  0.1  0.0 1066072 1996 ?        Sl   10:07   0:04 /opt/app-root/bin/python python/eggroll/roll_pair/egg_pair.py --config /data/projects/fate/eggroll/conf/eggroll.properties --session-id 202302101007038548750_reader_0_0_guest_60003_storage_a4ce30c8-a8e7-11ed-92bc-0242c0a70064 --server-node-id 2 --cluster-manager clustermanager:4670 --node-manager 4671 --processor-id 13009
root       1216  0.2  0.4 1697136 65044 ?       Sl   10:07   0:07 /opt/app-root/bin/python python/eggroll/roll_pair/egg_pair.py --config /data/projects/fate/eggroll/conf/eggroll.properties --session-id 202302101007038548750_sample_0_0_guest_60003 --server-node-id 2 --cluster-manager clustermanager:4670 --node-manager 4671 --processor-id 13015
root       1230  0.2  0.3 1770868 63712 ?       Sl   10:07   0:07 /opt/app-root/bin/python python/eggroll/roll_pair/egg_pair.py --config /data/projects/fate/eggroll/conf/eggroll.properties --session-id 202302101007038548750_sample_0_0_guest_60003 --server-node-id 2 --cluster-manager clustermanager:4670 --node-manager 4671 --processor-id 13012
root       1237  0.2  0.4 1697136 66632 ?       Sl   10:07   0:07 /opt/app-root/bin/python python/eggroll/roll_pair/egg_pair.py --config /data/projects/fate/eggroll/conf/eggroll.properties --session-id 202302101007038548750_sample_0_0_guest_60003 --server-node-id 2 --cluster-manager clustermanager:4670 --node-manager 4671 --processor-id 13016
root       1239  0.2  0.4 1770868 72040 ?       Sl   10:07   0:08 /opt/app-root/bin/python python/eggroll/roll_pair/egg_pair.py --config /data/projects/fate/eggroll/conf/eggroll.properties --session-id 202302101007038548750_sample_0_0_guest_60003 --server-node-id 2 --cluster-manager clustermanager:4670 --node-manager 4671 --processor-id 13013
root       1244  0.2  0.4 1697136 69988 ?       Sl   10:07   0:07 /opt/app-root/bin/python python/eggroll/roll_pair/egg_pair.py --config /data/projects/fate/eggroll/conf/eggroll.properties --session-id 202302101007038548750_sample_0_0_guest_60003 --server-node-id 2 --cluster-manager clustermanager:4670 --node-manager 4671 --processor-id 13014

**Comment by zhihuiwan** [comment]
请问下部署模式是怎样的？eggroll的计算节点有几个？
