### ISSUE TITLE
fate 数据接入-表绑定 table_bind的问题

### ISSUE THREAD

**Issue by LemonGitMin** [FederatedAI/FATE-Flow#411]
![fe641329d89327a476e62e117f1955f](https://user-images.githubusercontent.com/35891255/221472768-f3f91e50-f726-4c87-8bcf-7e7ae2467d8b.png)
1、请问下fate 数据接入-表绑定 支持传入指定的sql 语句吗 ？支持的话参数应该怎么传？
2、以上截图中 address.db 是mysql数据库名称？address.name是库中表的名称么？

**Comment by zhihuiwan** [comment]
1. 不支持；
2. address的db和name分别是指数据库的库表名称。
