### ISSUE TITLE
联邦参与方是通过proxy取得调度方发送的任务，对应的proxy是哪一块代码在进行任务的接收和转发？对应的fate_flow是哪块代码和proxy沟通

### ISSUE THREAD

**Issue by YuChangF** [FederatedAI/FATE-Flow#419]
联邦参与方是通过proxy取得调度方发送的任务，对应的proxy是哪一块代码在进行任务的接收和转发？对应的fate_flow是哪块代码和proxy沟通
代码能补充点注释吗，不然阅读起来会有点困难

**Comment by zhihuiwan** [comment]
您是指哪个版本？注释的话后续我们会接受您的建议，多加些注释。

**Comment by YuChangF** [comment]
1.10版本
