### ISSUE TITLE
fix spark config in role does not take effect

### ISSUE THREAD

**Issue by MDGBDGMG** [FederatedAI/FATE-Flow#424]
**System information**
fate on spark on rabbitmq v1.10.0

- Have I written custom code (yes/no):  no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Centos7.9
- FATE Flow version (use command: python fate_flow_server.py --version):  1.10.0
- Python version (use command: python --version):  3.8

**Describe the current behavior**
在conf文件中，`"job_parameters"`中的`"common"`配置了"spark_run"参数`"executor-cores":2`，同时，在`"component_parameters"`的`"role"`的`"host"`、`"guest"`、`"arbiter"`分别配置了`"spark_run"`参数`"executor-cores":6`、`"executor-cores":6`、`"executor-cores":2`

由于`"component_parameters"`的`"role"`的配置优先级高于`"job_parameters"`中的`"common"`，应当以`"component_parameters"`的`"role"`的`"spark_run"`配置为准，但是实际上以`"job_parameters"`中的`"common"`执行`“spark-submit”`

![image](https://user-images.githubusercontent.com/45615979/232692629-387eec22-f20b-423a-9b39-9a158a75ee78.png)
执行spark-submit时，host、guest、arbiter的executor-cores都是2

guest方执行spark-submit的日志，executor-cores是2，应当是6
![image](https://user-images.githubusercontent.com/45615979/232692816-d949ab13-df2f-40a0-9eeb-0bfe59761897.png)
host方执行spark-submit的日志，executor-cores是2，应当是6
![image](https://user-images.githubusercontent.com/45615979/232693673-68ea3c4c-df53-4307-9129-028db3003de9.png)

**Describe the fix behavior**
查看源代码，发现RuntimeConfParserUtil.merge_dict就是对config的优先级排序整合的代码，但调用RuntimeConfParserUtil.merge_dict有问题
取role的config参数时，取错了key
[        role_job_parameters = job_parameters.get("role", {})
](https://github.com/FederatedAI/FATE-Flow/blob/cee0306a687a0a909bcfb8d4b7daca3a6caca690/python/fate_flow/utils/runtime_conf_parse_util.py#L543)

"role_job_parameters "在"component_parameters"中，而不是在"job_parameters"中
![image](https://user-images.githubusercontent.com/45615979/232695585-e4454306-c47e-4474-9836-52b241b9541a.png)

修改代码
https://github.com/FederatedAI/FATE-Flow/blob/v1.10.0/python/fate_flow/utils/runtime_conf_parse_util.py
![image](https://user-images.githubusercontent.com/45615979/232695846-a83a6e5b-11b0-4519-a930-b279b1257c25.png)

修改调用链
https://github.com/FederatedAI/FATE-Flow/blob/v1.10.0/python/fate_flow/scheduler/dsl_parser.py
![image](https://user-images.githubusercontent.com/45615979/232696268-ae1a8ced-e0d6-4b3d-ba97-685cd87de3bb.png)

https://github.com/FederatedAI/FATE-Flow/blob/v1.10.0/python/fate_flow/controller/job_controller.py
![image](https://user-images.githubusercontent.com/45615979/232696334-66ae6c50-ae29-4b51-9af8-058deef2c06b.png)

https://github.com/FederatedAI/FATE-Flow/blob/v1.10.0/python/fate_flow/worker/task_executor.py
![image](https://user-images.githubusercontent.com/45615979/232696468-7570a99e-2a47-43b9-9701-a57eb1a44314.png)

修改完毕以后，部署新代码
提交job，得到预期结果
配置common中的spark_run的executor-cores均为6
配置host的spark_run的executor-cores为14
配置guest的spark_run的executor-cores为16
配置arbiter的spark_run的executor-cores为2
配置文件：
`{
        "job_parameters":{
                "common":{
                        "computing_engine":"SPARK",
                        "computing_partitions":1,
                        "federated_status_collect_type":"PUSH",
                        "spark_run":{
                             "executor-cores":6
                          },
                        "federated_mode":"MULTIPLE"
                }
        },
        "component_parameters":{
                "role":{
                        "host":{
                                "0":{
                                        "spark_run":{
                                                "executor-cores":14
                                        },
                                        "reader_2":{
                                                "table":{
                                                        "name":"breast_hetero_host1",
                                                        "namespace":"breast_hetero_host1"
                                                }
                                        }
                                }
                        },
                        "guest":{
                                "0":{
                                        "spark_run":{
                                               "executor-cores":16
                                        },
                                        "reader_2":{
                                                "table":{
                                                        "name":"breast_hetero_guest1",
                                                        "namespace":"breast_hetero_guest1"
                                                }
                                        }
                                }
                        },
                        "arbiter":{
                                "0":{
                                        "spark_run":{
                                                   "executor-cores":2
                                        }
                                }
                        }
                }
        },
        "dsl_version":2,
        "role":{
                "arbiter":[
                        1639998474
                ],
                "host":[
                        1639998474
                ],
                "guest":[
                        1639995892
                ]
        },
        "initiator":{
                "role":"guest",
                "party_id":1639995892
        }
}`

![image](https://user-images.githubusercontent.com/45615979/232699531-ca392fe7-b50f-4830-b797-01c245dbf65d.png)

host方执行spark-submit的日志，executor-cores是14，应当是14。符合预期
![image](https://user-images.githubusercontent.com/45615979/232700791-ff7b72e1-f6cf-4100-9531-f474c819f919.png)

guest方执行spark-submit的日志，executor-cores是16，应当是16。符合预期
![image](https://user-images.githubusercontent.com/45615979/232700444-8e9129e5-244b-402d-9e6f-5e1bd93dc5fb.png)

arbiter方执行spark-submit的日志，executor-cores是2，应当是2。符合预期
![image](https://user-images.githubusercontent.com/45615979/232701414-f444225f-9ade-42e7-a19d-04d366d77883.png)

**Describe the expected behavior**

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

- fateflow/logs/$job_id/fate_flow_schedule.log: scheduling log for a job
- fateflow/logs/$job_id/* : all logs for a job
- fateflow/logs/fate_flow/fate_flow_stat.log: a log of server stat
- fateflow/logs/fate_flow/fate_flow_schedule.log: the starting scheduling log for all jobs
- fateflow/logs/fate_flow/fate_flow_detect.log: the starting detecting log for all jobs

**Contributing**

代码已经写好了，没有push权限

- Do you want to contribute a PR? (yes/no): yes
- Briefly describe your candidate solution(if contributing): fix spark config in role does not take effect

**Comment by zhihuiwan** [comment]
你可以将代码fork到自己个人仓库，然后将修改提交到个人仓库，并提交一个pr到此仓库。

**Comment by zhihuiwan** [comment]
fork master分支并且先pr到master分支(后续可以切换)

**Comment by MDGBDGMG** [comment]
已提交PR:  https://github.com/FederatedAI/FATE-Flow/pull/428
