### ISSUE TITLE
请问 SecureAddExample 组件是否支持多方验证

### ISSUE THREAD

**Issue by awencai** [FederatedAI/FATE-Flow#455]
目前我部署了三个节点 1，2，3，想测试三个节点的连通性。我看 toy 是用了 `SecureAddExample` 作为双边测试，这里请教一下，是否可以用 `SecureAddExample` 做多边测试，如果可以的话 runtime_conf 和 dsl_conf 如何配置。

**Comment by awencai** [comment]
另外请问一下是否有其他测试连通性的方法

**Comment by zhihuiwan** [comment]
目前是不支持的，后续版本可以支持

**Comment by awencai** [comment]
> 目前是不支持的，后续版本可以支持

好的 谢谢
