### ISSUE TITLE
线程block，无法退出

### ISSUE THREAD

**Issue by zchunhai** [FederatedAI/FATE-Flow#496]
https://github.com/FederatedAI/FATE-Flow/blob/c8167883fbfc69afdcfedbdded2f400f8f7b289c/python/fate_flow/utils/xthread.py#L69

这段代码，某些异常情况下会永久block，导致线程无法退出，线程数持续增长。
建议加一个timeout参数，同时捕获Empty exception 。

@zhihuiwan

**Comment by zhihuiwan** [comment]
您可以尝试使用下最新版本，看看是否还有此问题。此issue我先关闭了， 如果还有问题您可以重新打开。
